### ISSUE TITLE
chinese support

### ISSUE THREAD

**Issue by guozhizou** [rhythmx/resume#1]
fantastic resume tempalate!
I wanna use it as my resume tempalate, but chinese characters are not displayed properly, how to solve it.

thx in advance!

**Comment by rhythmx** [comment]
I believe that it normally works out of the box, but the fonts I am using probably have poor support for any Chinese codepoints. You'd probably have some luck just swapping out for new fonts and playing around with sizes/alignments until it all looks nice again.

**Comment by guozhizou** [comment]
yeah, fonts matter.
